###############################################################################
#
#   Packages in conda virtual environment for MAPP
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 20-03-2020
#   LICENSE: Apache_2.0
#
###############################################################################
---

name: paqr2-main

channels:
  - bioconda
  - conda-forge

dependencies:
  - bash=4.4.18
  - snakemake=5.19.0
  - python=3.7.4
  - pandas=1.0.1
  - graphviz=2.38.0

...
