###############################################################################
#
#   Packages in conda virtual environment for PAQR
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 20-03-2020
#   LICENSE: Apache_2.0
#
###############################################################################
---

name: paqr2

channels:
  - conda-forge
  - main

dependencies:
  - bash=4.4.18
  - python=3.7.4
  - pip=20.0.2
  - pandas=1.0.1
  - graphviz=2.40.1
  - mamba
  - tabulate=0.8.10
  - pip:
    - snakemake==6.5.5

...
