name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:

  snakemake-dag:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout paqr2 repository
        uses: actions/checkout@v2

      - name: Setup miniconda & paqr2 root env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7.4
          auto-update-conda: false
          environment-file: install/environment.yml
          activate-environment: paqr2
          auto-activate-base: false

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list
